### ISSUE TITLE
Registration Error: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by mthnglac** [iMerica/dj-rest-auth#18]
There is a problem in the part of the documentation described as registration.
I am trying to make the user a member using the `'dj-rest-auth /registration/'` url. My purpose is to be able to login, logout and register users using simplejwt. However, at this stage, the application automatically tries to send email and gives an error.

I tried to reach the source of the problem in order to help. `allauth` is fully refused while trying to send email here (at line 3): 

- allauth/accounts/adapter.py

```
    def send_mail(self, template_prefix, email, context):
        msg = self.render_mail(template_prefix, email, context)
        msg.send()
```

Afterwards, when I looked through the **admin** panel, I saw that the user was a member, but the tokens were not processed in the token table. Then, when I tried `/dj-rest-auth/login/` url, I got **_'access'_**, **_'refresh'_** tokens and user information as a response. Every time I log in, different tokens come in and data cannot be received with these tokens.

And again afterwards, when I try to delete the user from the admin panel, I get the error:

`no such table: allauth_socialaccount`

It asks me to specify this application in the settings file; which I thought we used it in social authentication, I was a bit confused about it. When I added **_'allauth.socialaccount'_** to **_'INSTALLED_APPS'_** in setttings file, the problem was solved, so I was able to delete the user from the admin panel.

So there is a big chain of problems here.

1. register (partly making a member, then it gets refused when sending email and gives error)

2. login (gives the user different tokens that are not kept in the database in each login and data cannot be received)

3. OperationalError while user deletion in django admin panel (instructions written in the registration section of the documentation does not work )

**Comment by bugraaydogar** [comment]
Hi Metehan,

As I understand, your problem is that, you could not really register the user to the system. Therefore, you also started to see different problems ( about tokens in login ) which in turn directly related with registration trouble you have.

So , first and most importantly, you must configure and activate your email settings in Django.

EMAIL_HOST = 'get-from-email-provider'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'get-from-email-provider'
EMAIL_HOST_PASSWORD = 'get-from-email-provider'
DEFAULT_FROM_EMAIL = 'hello@yourdomain.com'

Please be sure, that you are able to send registration email and share your feedback. I believe, this will help you with your questions number 1 and 2.

I hope it helps,
Bugra

**Comment by mthnglac** [comment]
@bugraaydogar  I tried the suggestion and I have solved **_problem 1_**. E-mail was sent and then  the registration screen has successfully provided user information (access, refresh, username, email). 

However, **_problem 2_** still continues. Tokens are not kept in the database and I cannot also withdraw data with tokens.

**Comment by mthnglac** [comment]
Oops sorry. **_simplejwt_** did not keep the tokens in its database. I checked its documents again. The tokens I received from the registration screen are working properly. so **_problem 2_** solved.
