### ISSUE TITLE
missing settings variables in doc

### ISSUE THREAD

**Issue by egorgam** [iMerica/dj-rest-auth#300]
Hello! In my case i wont to use registration without sending email, but i don't see documentation info about it. Templorary I can use EMAIL_BACKEND = 'django.core.mail.backends.locmem.EmailBackend' but... what a native way to implement it?

**Comment by escaper01** [comment]
Let me get this straight, YOU want to make the registration process without verification email :
in that use you can use
`ACCOUNT_EMAIL_VERIFICATION = "none"
`
this settings can be found [here](https://django-allauth.readthedocs.io/en/latest/configuration.html)
 since [dj-rest-auth](https://github.com/iMerica/dj-rest-auth) is depending on [django-allauth](https://github.com/pennersr/django-allauth)
