### ISSUE TITLE
How to update the account_emailaddress model ?

### ISSUE THREAD

**Issue by R-P-H** [iMerica/dj-rest-auth#416]
Hi, how can I access the built in email_addresses model ? I would like to do the following:

1) Through my custom _**create_superuser**_ class I need to create an entry in **_account_emailaddress_** else I get an email not verified error.

2) When a user updates their **_email_** I would like to also update their email in the **_account_emailaddress_** model and set **_verified_** back to **false**.

Is this possible ?

**Comment by iMerica** [comment]
You can do this by overriding the classes in this library.

**Comment by Routhinator** [comment]
Can we reopen this and mark as a docs task? Would be good to document this as migrating from another auth solution that just uses the `email` field on the usermodel requires this to be fixed somehow, otherwise posting a new user email address to the /auth/user/ endpoint causes the user to be locked out with no way to verify the new email as there is no entry created in the `account_emailaddress` table.
